name: Email Action Trigger

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f3001900@ds.study.iitm.ac.in
        run: echo "Hello, world!"